# Generated by Django 4.1.7 on 2023-03-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagem',
        ),
        migrations.AddField(
            model_name='produto',
            name='image',
            field=models.FileField(default='', upload_to='products/'),
            preserve_default=False,
        ),
    ]
