# Generated by Django 4.1 on 2023-03-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_carrinho_pedido_itempedido_itemcarrinho_favorito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='valor_total',
            field=models.FloatField(),
        ),
    ]
